#!/usr/bin/env bash

set -euo pipefail

RSYNC_ARGS="${RSYNC_ARGS:---archive --partial --progress}"

scriptdir=$(cd "$(dirname "$0")" && pwd)

# shellcheck source=./common.sh
. "$scriptdir/common.sh"

process_arguments "$@"
shift $((OPTIND - 1))

if [ $# -lt 2 ]; then
    die "Usage: %s SOURCE DESTINATION [ARGS..]" "${0##*/}"
fi
source=$1
shift
dest=$1
shift

if [ -n "$directory" ]; then
    mkdir -p "$directory"
    cd "$directory"
fi

if [ -e "$dest/.done" ] && [ -z "$update" ]; then
    exit 0
fi

# shellcheck disable=SC2086
rsync ${ARGS:-$RSYNC_ARGS} "$@" "$source" "$dest"

touch "$dest/.done"
