#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd)

# shellcheck source=./common.sh
. "$scriptdir/common.sh"

process_arguments "$@"
shift $((OPTIND - 1))

if [ -n "$directory" ]; then
    mkdir -p "$directory"
    cd "$directory"
fi

export ARG_VERBOSE="$verbose"
export ARG_UPDATE="$update"

# Main
"$@"
