#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd)

# shellcheck source=./common.sh
. "$scriptdir/common.sh"

process_arguments "$@"
shift $((OPTIND - 1))

if [ $# -lt 1 ]; then
    die "Usage: %s PROJECT [ARGS...]" "${0##*/}"
fi

project=$1
shift

if [ -n "$directory" ]; then
    mkdir -p "$directory"
    cd "$directory"
    if [ -e ".done" ] && [ -z "$update" ]; then
        exit 0
    fi
fi

sf-download ${verbose:+-v} ${update:+-u} ${ARGS:+-a "$ARGS"} "$@" "$project"

if [ -n "$directory" ]; then
    touch ".done"
fi
