#!/usr/bin/env bash

set -euo pipefail

WAYBACK_ARGS="${WAYBACK_ARGS:---all-timestamps}"

scriptdir=$(cd "$(dirname "$0")" && pwd)
PATH="$scriptdir:$scriptdir/extras:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh"

url_dest() {
    local url=$1
    dest="${url#*://}"
    case "$dest" in
    */) ;;
    *)
        dest="$(dirname "$dest")"
        ;;
    esac
    echo "$dest"
}

ARGS="$WAYBACK_ARGS"
process_arguments "$@"
shift $((OPTIND - 1))

if [ $# -lt 1 ]; then
    die "Usage: %s URL [DESTINATION [ARGS..]]" "${0##*/}"
fi
url=$1
shift
if [ $# -gt 0 ]; then
    dest=$1
    shift
else
    if has unfurl; then
        dest="$(echo "$url" | unfurl domains)_IA"
    else
        dest=$(url_dest "${url%/*}")_IA
    fi
fi

if [ -n "$directory" ]; then
    mkdir -p "$directory"
    cd "$directory"
fi

if [ -e "$dest/.done" ] && [ -z "$update" ]; then
    exit 0
fi

list_timestamped() {
    find "$1" -mindepth 1 -maxdepth 1 -type d ${2:+$2} -iname '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
}

list_not_timestamped() {
    list_timestamped "$1" -not
}

# shellcheck disable=SC2086
run wayback_machine_downloader ${ARGS:+$ARGS} "$@" -d "$dest" "$url"
# shellcheck disable=SC2046
if [ $(list_timestamped "$dest" | wc -l) -gt 0 ] && [ $(list_not_timestamped "$dest" | wc -l) -eq 0 ]; then
    run wayback-merge "$dest" "${dest%/}_merged"
fi

touch "$dest/.done"
