#!/usr/bin/env bash

set -euo pipefail

WGET_ARGS="${WGET_ARGS:---mirror -N -kxK -l 0 -np -e robots=off --user-agent "InconspiuousWebBrowser/1.0" --random-wait --content-disposition}"

scriptdir=$(cd "$(dirname "$0")" && pwd)

# shellcheck source=./common.sh
. "$scriptdir/common.sh"

url_dest() {
    local url
    url=$(urldecode "$1")
    dest="${url#*://}"
    case "$dest" in
    */) ;;
    *)
        dest="$(dirname "$dest")"
        ;;
    esac
    echo "$dest"
}

urldecode() {
    python3 -c "import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1]))" "$1"
}

unfurl_dest() {
    unfurl json | jq -r '.domain + "/" + .path'
}

process_arguments() {
    ARGS=${WGET_ARGS:-}
    common_process_arguments "$@"
    shift $((OPTIND - 1))

    ORIG_OPTIND=$OPTIND
    OPTIND=0
    dest=
    wget2=
    while getopts 12D:h opt; do
        case "$opt" in
            1)
                wget2=
                ;;
            2)
                wget2=1
                ;;
            D)
                dest="$OPTARG"
                ;;
            \? | h)
                usage
                ;;
        esac
    done
    shift $((OPTIND - 1))

    OPTIND=$((OPTIND + ORIG_OPTIND - 1))
}

process_arguments "$@"
shift $((OPTIND - 1))

if [ $# -lt 1 ]; then
    die "Usage: %s URL [ARGS..]" "${0##*/}"
fi
url=$1
shift

if [ -z "$dest" ]; then
    case "$url" in
    */)
        adjusted="$url"
        ;;
    *)
        adjusted="$(dirname "$url")"
        ;;
    esac

    if has unfurl; then
        dest="$(echo "$adjusted" | unfurl_dest)"
    else
        dest="$(url_dest "${adjusted%/}/")"
    fi
fi

if [ -n "$directory" ]; then
    mkdir -p "$directory"
    cd "$directory"
fi

if [ -e "$dest/.done" ] && [ -z "$update" ]; then
    exit 0
fi

# shellcheck disable=SC2086
wget${wget2:+2} ${ARGS:+$ARGS} "$@" "$url"

find "$dest" -name index.html.tmp -delete
touch "$dest/.done"
