#!/usr/bin/env bash

set -euo pipefail

WGET_ARGS="${WGET_ARGS:---mirror -kxK -l 0 -np -e robots=off}"

scriptdir=$(cd "$(dirname "$0")" && pwd)

# shellcheck source=./common.sh
. "$scriptdir/common.sh"

url_dest() {
    local url
    url=$(urldecode "$1")
    dest="${url#*://}"
    case "$dest" in
    */) ;;
    *)
        dest="$(dirname "$dest")"
        ;;
    esac
    echo "$dest"
}

urldecode() {
    python3 -c "import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1]))" "$1"
}

unfurl_dest() {
    unfurl json | jq -r '.domain + "/" + .path'
}

ARGS="$WGET_ARGS"
process_arguments "$@"
shift $((OPTIND - 1))

if [ $# -lt 1 ]; then
    die "Usage: %s URL [ARGS..]" "${0##*/}"
fi
url=$1
shift

case "$url" in
*/)
    adjusted="$url"
    ;;
*)
    adjusted="$(dirname "$url")"
    ;;
esac

if has unfurl; then
    dest="$(echo "$adjusted" | unfurl_dest)"
else
    dest="$(url_dest "${adjusted%/}/")"
fi

if [ -n "$directory" ]; then
    mkdir -p "$directory"
    cd "$directory"
fi

if [ -e "$dest/.done" ] && [ -z "$update" ]; then
    exit 0
fi

# shellcheck disable=SC2086
wget ${ARGS:+$ARGS} "$@" "$url"

touch "$dest/.done"
